run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - ineffassign
    - gofmt
    - goimports
    - gocyclo
    - revive
    - bodyclose

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
